# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 52ee23b9a514623db5dc9c7efa0e39ffa237742d038a71657745619df5625ecff33e52415cc4b6a94e4ec497222fd447dee5e0d804f8392d5debf61149c73849

test:
  secret_key_base: a33fd57677333a0329235adc241bc21beb6b36bb6bf4b27e757c60e853f497e8aa44863fea117c057e91a0aada01afa4cce001e0895392e5340e0e01f410c0a2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
